# Incertidumbre

Asumimos que en un año se pueden tener dos estados diferentes: 
- $u$ que representa una mejora
- $d$ que representa un empeoramiento

Por ejemplo los flujos de caja de un proyecto vienen definidos por una vector 
$$c_1 \in \mathbb{R}^2$$
Con dos posibles estados de la naturaleza:
$$c_1^u, c_1^d \in \mathbb{R}$$

Por tanto:
$$c_1=\left(\begin{array}{crl}
c_1^u\\
c_1^d
\end{array}\right)$$

Matemáticamente recordamos que:
$$\alpha·c_1+\beta=\alpha \left(\begin{array}{crl}
c_1^u\\
c_1^d
\end{array}\right)+ \beta=\left(\begin{array}{crl}
\alpha ·c_1^u+ \beta\\
\alpha ·c_1^d+ \beta
\end{array}\right) $$

Supongamos que ahora tenemos otro vector $d_1$ que representa otro activo:
$$\alpha·c_1+\beta· d_1=\left(\begin{array}{crl}
\alpha ·c_1^u+ \beta·d_1^u \\
\alpha ·c_1^d+ \beta· d_1^d
\end{array}\right) $$

In [72]:
import numpy as np

In [73]:
c0 = -10
c1 = np.array((20, 5))

In [74]:
type(c1)

numpy.ndarray

In [75]:
c1

array([20,  5])

In [76]:
c = (c0, c1)

In [77]:
c

(-10, array([20,  5]))

In [78]:
1.5 * c1 + 2

array([32. ,  9.5])

In [79]:
c1 + 1.5 * np.array((10, 4))

array([35., 11.])

# Activo Financiero

El precio actual es $S_0 \in \mathbb{R}$. Suponemos que sólo puede tener dos precios transcurrido un periodo $S_1^u, S_1^d \in \mathbb{R}$ con  $S_1^u > S_1^d$. La evolución del precio de una activo financiero viene definida por $S: \mathbb{N}_0 \times \rightarrow \mathbb{R}_{\geq 0}$ representa la reacción temporal del activo ante los posibles estados de la economía.

In [80]:
S0 = 10
S1 = np.array((12.5, 7.5))
S = (S0, S1)
S

(10, array([12.5,  7.5]))

In [81]:
S[0]

10

In [82]:
S[1][0]

12.5

# Riesgo

Podemos asignar a cada estado de la naturaleza una probabilidad de ocurrencia $p\in \mathbb{R}_{\geq 0}$ con $0\leq p \leq 1$

## Medida de probabilidad

La medida de probabilidad es una función $P :\wp (\{u,d\}) \leftarrow \mathbb{R}_{\geq 0}$ asignando todos los elementos del conjunto de potencias de $\{u,d\}$ al intervalo unitario. En este caso, el conjunto de potencias engloba todos los sucesos físicamente posibles.

En este contexto el conjunto $\{u,d\}$ también se denomina espacio de estados y se simboliza mediante $\Omega$. La tripleta $(\Omega, \wp (\Omega), P)$ define el espacio probabilístico.

Para que una función $P$ se pueda considerar una medida de probabilidad debe cumplir tres condiciones:
1. $P(\emptyset)=0$
2. $0\leq P(\omega),\omega \in \Omega \leq 1$
3. $P(\Omega)=P(u)+P(d)=1$

En un modelo simple de dos estados posibles es conveniente $P(u)=p$ y que $P(d)=1-p$. Con ello estamos definiendo una economía con riesgo

In [83]:
p=0.4
P=np.array((p,1-p))
P

array([0.4, 0.6])

## Expectativas

Basado en una medida de la probabilidad  las expectativas de una cantidad incierta puede ser estimada.

Disponemos de un activo financiero con un proceso de precios $S=(S_0, S_1)$. Las expectativas sobre el precio incierto $P_1$ con una función de probabilidad $P$.
$$\textbf{E}^P(S_1)=\sum_{\omega \in \Omega}P(\omega)·S_1^\omega=p·S_1^u+(1-p)S_1^d$$

Si $S_1=(20,5)^T$ y $p=0.4$:

$$\textbf{E}^P(S_1)=0.4·20+(1-0.4)·5=11$$

Matricialmente $P=(p,1-p)^T$ y $S_1=(S_1^u,S_1^d)^T$ las expectativas son:
$$\textbf{E}^P(S_1)=(P,S_1)=\left(\left( \begin{array}{crl}p \\ 1-p \end{array}\right),\left( \begin{array}{crl}S_1^u \\ S_1^d \end{array}\right)\right)=p·S_1^u+(1-p)·S_1^d$$


In [111]:
P

array([0.4, 0.6])

In [85]:
S0 = 10
S1 = np.array((20, 5))

In [86]:
np.dot(P, S1)

11.0

## Rentabilidad Esperada

El rendimiento esperado de un activo financiero $R=(R^u, R^d)^T$ podría expresarse del siguiente modo:
$$\begin{align}
\textbf{E}^P(R)&=\left(\left( \begin{array}{crl}p \\ 1-p \end{array}\right),\left( \begin{array}{crl}R^u \\ R^d \end{array}\right)\right) \\
&=\left(\left( \begin{array}{crl}p \\ 1-p \end{array}\right),\left( \begin{array}{crl}S_1^u-S_0 \\ S_1^d-S_0 \end{array}\right)\right) \\
&=p·(S_1^u-S_0)+(1-p)·(S_1^d-S_0) \\
&= p·S_1^u++(1-p)·S_1^d-S_0 \\
&= \textbf{E}^P(S_1)-S_0
\end{align}$$

Si lo aplicamos a nuestro ejemplo:

$$\textbf{E}^P(R)=0.4·(20-10)+(1-0.4)·(5-10)=11-10=1$$

La rentabilidad esperada la definimos como:

$$\textbf{E}^P(r)=\frac{\textbf{E}^P(R)}{S_0}$$

La rentabilidad esperada se suele expresar $\mu=\textbf{E}^P(r)$

In [87]:
def ER(x0, x1):
    return np.dot(P, x1) - x0

In [88]:
ER(S0, S1)

1.0

In [89]:
def mu(x0, x1):
    return (np.dot(P, x1) - x0) / x0

In [90]:
mu(S0, S1)

0.1

# GRAFICOS COMPARANDO TIPOS DE ACTIVOS Y LA VARIACIÓN DE LA RENTABILIDAD

## Volatilidad

En finanzas todo gira en torno al riesgo y la rentabilidad esperada. El riesgo puede ser medido de distintas maneras pero la volatilidad es la desviación típica de la rentabiliad. Así, la varianza de la rentabilidad será:
$$\begin{align}
\sigma^2(r) &=\textbf{E}^P \left(\left( r-\mu \right)\right) \\
&=\left(\left(\begin{array}{crl} p \\ 1-p \end{array} \right),\left(\begin{array}{crl} (r^u-\mu)^2 \\ (r^d-\mu)^2  \end{array}\right)\right)
\end{align}$$

Con $R^{\omega}\equiv (S_1^\omega - S_0)/S_0, \omega \in \Omega$. La volatilidad definida como desviación típica de la rentabilidad será:
$$\sigma(r)=\sqrt{\sigma^2(r)}$$

In [91]:
def r(x0, x1):
    return (x1 - x0) / x0

In [92]:
r(S0, S1)

array([ 1. , -0.5])

In [93]:
mu = np.dot(P, r(S0, S1))
mu

0.10000000000000003

In [94]:
def sigma2(P, r, mu):
    return np.dot(P, (r - mu) ** 2)

In [95]:
sigma2(P, r(S0, S1), mu)

0.54

In [96]:
def sigma(P, r, mu):
    return np.sqrt(np.dot(P, (r - mu) ** 2))

In [97]:
sigma(P, r(S0, S1), mu)

0.7348469228349535